### ISSUE TITLE
Hello,I meet the problem,when I install the pycolmap,I have already install the colmap.

### ISSUE THREAD

**Issue by bobododosjl** [colmap/pycolmap#110]

**Comment by bobododosjl** [comment]
pycolmap git:(master) sudo pip install .
WARNING: The directory '/home/sjl/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/sjl/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Looking in indexes: http://pypi.douban.com/simple
Processing /home/sjl/pycolmap
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-okvluhex/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-okvluhex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-okvluhex/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-okvluhex/setup.py", line 58
        cmake_args += [f'-DCMAKE_TOOLCHAIN_FILE={cmake_toolchain_file}']
                                                                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sarlinpe** [comment]
Not enough info for debugging, closing due to inactivity.
