### ISSUE TITLE
build from source met error: ‘ba_global_use_pba’ is not a member of ‘Opts’ {aka ‘colmap::IncrementalMapperOptions’}

### ISSUE THREAD

**Issue by feiyangsuo** [colmap/pycolmap#120]
First of all, thanks for your great work.
I'm trying to build pycolmap with colmap already built with CUDA.

I got an error reads 
```
In file included from /mnt/workspace/pycolmap/main.cc:22:
      /mnt/workspace/pycolmap/pipeline/sfm.cc: In function ‘void init_sfm(pybind11::module&)’:
      /mnt/workspace/pycolmap/pipeline/sfm.cc:152:56: error: ‘ba_global_use_pba’ is not a member of ‘Opts’ {aka ‘colmap::IncrementalMapperOptions’}
``` 
while building pycolmap (Is this due to the incompatible versions of colmap and pycolmap?). 

Environment:
- Ubuntu 20.04.5 LTS
- gcc version 9.4.0
- python 3.9.15
- cuda-toolkit 11.4

Full stack:
```
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Processing /mnt/workspace/pycolmap
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      running bdist_wheel
      running build
      running build_ext
      ['cmake', '/mnt/workspace/pycolmap', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/mnt/workspace/pycolmap/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE=/home/pai/bin/python', '-DVERSION_INFO=0.4.0', '-DCMAKE_BUILD_TYPE=Release']
      -- Found installed version of Eigen: /usr/lib/cmake/eigen3
      -- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
      -- Found required Ceres dependency: glog
      -- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
      -- Detected gflags version: 2.2.2
      -- Found required Ceres dependency: gflags
      -- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem system unit_test_framework
      -- Found Eigen
      --   Includes : /usr/include/eigen3
      -- Found FLANN
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
      -- Found LZ4
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
      -- Found FreeImage
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
      -- Found Glog
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
      -- Found SQLite3
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libsqlite3.so
      CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
        Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
        available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      
        FindOpenGL found both a legacy GL library:
      
          OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
      
        and GLVND libraries for OpenGL and GLX:
      
          OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
          OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
      
        OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
        compatibility with CMake 3.10 and below the legacy GL library will be used.
      Call Stack (most recent call first):
        /usr/local/share/colmap/COLMAPConfig.cmake:128 (find_package)
        CMakeLists.txt:4 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found Glew
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
      -- Using header-only CGAL
      -- Targetting Unix Makefiles
      -- Using /usr/bin/c++ compiler.
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
      -- Boost include dirs: /usr/include
      -- Boost libraries:
      -- Using gcc version 4 or later. Adding -frounding-math
      -- pybind11 v2.8.1
      -- Found PythonInterp: /home/pai/bin/python (found version "3.9.15")
      -- Found PythonLibs: /home/pai/lib/libpython3.9.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      Compiling bindings with CUDA support.
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /mnt/workspace/pycolmap/build/temp.linux-x86_64-cpython-39
      Scanning dependencies of target pycolmap
      [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
      In file included from /mnt/workspace/pycolmap/main.cc:22:
      /mnt/workspace/pycolmap/pipeline/sfm.cc: In function ‘void init_sfm(pybind11::module&)’:
      /mnt/workspace/pycolmap/pipeline/sfm.cc:152:56: error: ‘ba_global_use_pba’ is not a member of ‘Opts’ {aka ‘colmap::IncrementalMapperOptions’}
        152 |             .def_readwrite("ba_global_use_pba", &Opts::ba_global_use_pba)
            |                                                        ^~~~~~~~~~~~~~~~~
      /mnt/workspace/pycolmap/pipeline/sfm.cc:154:35: error: ‘ba_global_pba_gpu_index’ is not a member of ‘Opts’ {aka ‘colmap::IncrementalMapperOptions’}
        154 |                            &Opts::ba_global_pba_gpu_index)
            |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      /mnt/workspace/pycolmap/pipeline/sfm.cc:180:65: error: expected primary-expression before ‘>’ token
        180 |     auto mapper_options = PyIncrementalMapperOptions().cast<Opts>();
            |                                                                 ^
      /mnt/workspace/pycolmap/pipeline/sfm.cc:180:67: error: expected primary-expression before ‘)’ token
        180 |     auto mapper_options = PyIncrementalMapperOptions().cast<Opts>();
            |                                                                   ^
      make[2]: *** [CMakeFiles/pycolmap.dir/build.make:63: CMakeFiles/pycolmap.dir/main.cc.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/pycolmap.dir/all] Error 2
      make: *** [Makefile:84: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/workspace/pycolmap/setup.py", line 83, in <module>
          setup(
        File "/home/pai/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/pai/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pai/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/workspace/pycolmap/setup.py", line 35, in run
          self.build_extension(ext)
        File "/mnt/workspace/pycolmap/setup.py", line 78, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
        File "/home/pai/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycolmap
  Running setup.py clean for pycolmap
Failed to build pycolmap
Installing collected packages: pycolmap
  Running setup.py install for pycolmap ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycolmap did not run successfully.
  │ exit code: 1
  ╰─> [165 lines of output]
      running install
      /home/pai/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      ['cmake', '/mnt/workspace/pycolmap', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/mnt/workspace/pycolmap/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE=/home/pai/bin/python', '-DVERSION_INFO=0.4.0', '-DCMAKE_BUILD_TYPE=Release']
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found installed version of Eigen: /usr/lib/cmake/eigen3
      -- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
      -- Found required Ceres dependency: glog
      -- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
      -- Detected gflags version: 2.2.2
      -- Found required Ceres dependency: gflags
      -- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem system unit_test_framework
      -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
      -- Found Eigen
      --   Includes : /usr/include/eigen3
      -- Found FLANN
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
      -- Found LZ4
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
      -- Found FreeImage
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
      -- Found Glog
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
      -- Found SQLite3
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libsqlite3.so
      CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
        Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
        available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
        cmake_policy command to set the policy and suppress this warning.
      
        FindOpenGL found both a legacy GL library:
      
          OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
      
        and GLVND libraries for OpenGL and GLX:
      
          OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
          OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
      
        OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
        compatibility with CMake 3.10 and below the legacy GL library will be used.
      Call Stack (most recent call first):
        /usr/local/share/colmap/COLMAPConfig.cmake:128 (find_package)
        CMakeLists.txt:4 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
      -- Found Glew
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Using header-only CGAL
      -- Targetting Unix Makefiles
      -- Using /usr/bin/c++ compiler.
      -- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
      -- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
      -- Boost include dirs: /usr/include
      -- Boost libraries:
      -- Using gcc version 4 or later. Adding -frounding-math
      -- pybind11 v2.8.1
      -- Found PythonInterp: /home/pai/bin/python (found version "3.9.15")
      -- Found PythonLibs: /home/pai/lib/libpython3.9.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      Compiling bindings with CUDA support.
      -- Configuring done
      -- Generating done
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          VERSION_INFO
      
      
      -- Build files have been written to: /mnt/workspace/pycolmap/build/temp.linux-x86_64-cpython-39
      Scanning dependencies of target pycolmap
      [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
      In file included from /mnt/workspace/pycolmap/main.cc:22:
      /mnt/workspace/pycolmap/pipeline/sfm.cc: In function ‘void init_sfm(pybind11::module&)’:
      /mnt/workspace/pycolmap/pipeline/sfm.cc:152:56: error: ‘ba_global_use_pba’ is not a member of ‘Opts’ {aka ‘colmap::IncrementalMapperOptions’}
        152 |             .def_readwrite("ba_global_use_pba", &Opts::ba_global_use_pba)
            |                                                        ^~~~~~~~~~~~~~~~~
      /mnt/workspace/pycolmap/pipeline/sfm.cc:154:35: error: ‘ba_global_pba_gpu_index’ is not a member of ‘Opts’ {aka ‘colmap::IncrementalMapperOptions’}
        154 |                            &Opts::ba_global_pba_gpu_index)
            |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      /mnt/workspace/pycolmap/pipeline/sfm.cc:180:65: error: expected primary-expression before ‘>’ token
        180 |     auto mapper_options = PyIncrementalMapperOptions().cast<Opts>();
            |                                                                 ^
      /mnt/workspace/pycolmap/pipeline/sfm.cc:180:67: error: expected primary-expression before ‘)’ token
        180 |     auto mapper_options = PyIncrementalMapperOptions().cast<Opts>();
            |                                                                   ^
      make[2]: *** [CMakeFiles/pycolmap.dir/build.make:63: CMakeFiles/pycolmap.dir/main.cc.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/pycolmap.dir/all] Error 2
      make: *** [Makefile:84: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/workspace/pycolmap/setup.py", line 83, in <module>
          setup(
        File "/home/pai/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/pai/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pai/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/pai/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/workspace/pycolmap/setup.py", line 35, in run
          self.build_extension(ext)
        File "/mnt/workspace/pycolmap/setup.py", line 78, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
        File "/home/pai/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycolmap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

PS: As I execute `colmap`, I got:
```
COLMAP 3.9 -- Structure-from-Motion and Multi-View Stereo
              (Commit Unknown on Unknown with CUDA) 
```
which, I guess, indicates colmap is already built OK.

**Comment by awarebayes** [comment]
Same thing, colmap broke!

**Comment by feiyangsuo** [comment]
> Yes I had the same issue, it's because of this : [colmap/colmap#1840](https://github.com/colmap/colmap/pull/1840), so you have to build colmap before this change

Thanks. For now building colmap 3.8 instead of the latest version works for me. 
I believe it will be fixed later in pycolmap, and the bug no longer exists.

**Comment by JCRPaquin** [comment]
This should really be left open until the issue is resolved.

I just ran into this when trying to get [pixel-perfect-sfm](https://github.com/cvg/pixel-perfect-sfm) installed.

**Comment by JCRPaquin** [comment]
Looks like these are only being referenced as command line options? If you remove them from sfm.cc pycolmap compiles fine with the latest version of colmap.
