### ISSUE TITLE
Build fail with Ubuntu 22.04

### ISSUE THREAD

**Issue by xjcvip007** [colmap/pycolmap#136]
Hi, I'm trying to install pycolmap in Ubuntu 22.04 with Python 3.10.
I already installed CUDA 12.1 and built Ceres solver and COLMAP successfully.

I used pip to install pycolmap but error occurs, the output is attached below:

```
(base) netease@hih-d-16086:~/pycolmap-master/pybind11$ cd ..
(base) netease@hih-d-16086:~/pycolmap-master$ pip install ./
Processing /home/netease/pycolmap-master
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2714 lines of output]
      running bdist_wheel
      running build
      running build_ext
      ['cmake', '/home/netease/pycolmap-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/netease/pycolmap-master/build/lib.linux-x86_64-cpython-310', '-DPYTHON_EXECUTABLE=/home/netease/anaconda3/bin/python', '-DVERSION_INFO=0.4.0', '-DCMAKE_BUILD_TYPE=Release']
      -- Found AMD headers in: /usr/include/suitesparse
      -- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
      -- Found CAMD headers in: /usr/include/suitesparse
      -- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
      -- Found CCOLAMD headers in: /usr/include/suitesparse
      -- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
      -- Found CHOLMOD headers in: /usr/include/suitesparse
      -- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
      -- Found COLAMD headers in: /usr/include/suitesparse
      -- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
      -- Found SPQR headers in: /usr/include/suitesparse
      -- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
      -- Found Config headers in: /usr/include/suitesparse
      -- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
      -- Found Intel Thread Building Blocks (TBB) library (2021.5 / ) include location: . Assuming SuiteSparseQR was compiled with TBB.
      -- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
      -- Found required Ceres dependency: Eigen version 3.4.0 in /usr/share/eigen3/cmake
      -- Found required Ceres dependency: glog
      -- Found required Ceres dependency: gflags
      -- Found Ceres version: 2.1.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: program_options filesystem system unit_test_framework
      -- Found Eigen
      --   Includes : /usr/include/eigen3
      -- Found FLANN
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
      -- Found LZ4
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
      -- Found FreeImage
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
      -- Found Glog
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
      -- Found SQLite3
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libsqlite3.so
      -- Found Glew
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
      CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:92 (message):
        CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
        default value of CGAL::data_file_path()
      Call Stack (most recent call first):
        /usr/local/share/colmap/COLMAPConfig.cmake:224 (find_package)
        CMakeLists.txt:5 (find_package)
      
      
      -- Using header-only CGAL
      -- Targetting Unix Makefiles
      -- Using /usr/bin/c++ compiler.
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")
      -- Boost include dirs: /usr/include
      -- Boost libraries:
      -- Using gcc version 4 or later. Adding -frounding-math
      -- pybind11 v2.8.1
      Compiling bindings with CUDA support.
      Compiling bindings with CGAL support.
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /home/netease/pycolmap-master/build/temp.linux-x86_64-cpython-310
      [ 50%] Linking CXX shared module /home/netease/pycolmap-master/build/lib.linux-x86_64-cpython-310/pycolmap.cpython-310-x86_64-linux-gnu.so
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart729':
      (.text+0x10810): multiple definition of `__cudart729'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xc5a0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x5b8): multiple definition of `__cudart1032'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x528): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart889':
      (.text+0x5d50): multiple definition of `__cudart889'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x2760): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x710): multiple definition of `__cudart1403'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xf210): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart637':
      (.text+0x6e8a0): multiple definition of `__cudart637'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x65fd0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1113':
      (.text+0x8720): multiple definition of `__cudart1113'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x100c0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart982':
      (.text+0x7f30): multiple definition of `__cudart982'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x67c0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaGetDevice':
      (.text+0x3fab0): multiple definition of `cudaGetDevice'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x3d4f0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x788): multiple definition of `__cudart915'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.rodata+0x4050): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x5a8): multiple definition of `__cudart830'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x538): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1336':
      (.text+0xbd60): multiple definition of `__cudart1336'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x65ab0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart799':
      (.text+0x5ce0): multiple definition of `__cudart799'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x45a0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x9a0): multiple definition of `__cudart1455'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xca80): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x5f0): multiple definition of `__cudart1329'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x4880): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x478): multiple definition of `__cudart1317'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0xc0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart565':
      (.text+0x27550): multiple definition of `__cudart565'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x23b50): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x868): multiple definition of `__cudart876'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x960): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart495':
      (.text+0x34530): multiple definition of `__cudart495'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x214d0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x908): multiple definition of `__cudart1524'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xfc80): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaWaitExternalSemaphoresAsync_ptsz':
      (.text+0x61fd0): multiple definition of `cudaWaitExternalSemaphoresAsync_ptsz'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x5f370): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x608): multiple definition of `__cudart949'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x213e0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaStreamAddCallback':
      (.text+0x60770): multiple definition of `cudaStreamAddCallback'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x5dd20): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x438): multiple definition of `__cudart1421'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x860): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMemcpyArrayToArray':
      (.text+0x5cff0): multiple definition of `cudaMemcpyArrayToArray'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x5a790): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1342':
      (.text+0x35a0): multiple definition of `__cudart1342'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x3f8): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x1f8): multiple definition of `__cudart1239'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x770): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart535':
      (.text+0x27300): multiple definition of `__cudart535'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x23970): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x140): multiple definition of `__cudart757'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x2c0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaDeviceReset':
      (.text+0x3b940): multiple definition of `cudaDeviceReset'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x395a0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaGraphAddEventRecordNode':
      (.text+0x54d90): multiple definition of `cudaGraphAddEventRecordNode'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x52dd0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaGetSurfaceObjectResourceDesc':
      (.text+0x51880): multiple definition of `cudaGetSurfaceObjectResourceDesc'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x4f8c0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaGraphicsSubResourceGetMappedArray':
      (.text+0x50520): multiple definition of `cudaGraphicsSubResourceGetMappedArray'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x4d4d0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1479':
      (.text+0x3130): multiple definition of `__cudart1479'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xfa80): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0xa70): multiple definition of `__cudart1031'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x570): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart860':
      (.text+0x69fb0): multiple definition of `__cudart860'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x6b6f0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x6b8): multiple definition of `__cudart1514'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x58): first defined here

............................

      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1291':
      (.text+0xb710): multiple definition of `__cudart1291'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xb6a0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1301':
      (.text+0xc1d0): multiple definition of `__cudart1301'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x68990): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMemset2D_ptds':
      (.text+0x4baa0): multiple definition of `cudaMemset2D_ptds'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x48a90): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart940':
      (.text+0x6a120): multiple definition of `__cudart940'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x65a30): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart642':
      (.text+0x6df90): multiple definition of `__cudart642'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x67c70): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x840): multiple definition of `__cudart1425'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x690): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x720): multiple definition of `__cudart959'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0xa38): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart499':
      (.text+0x35b90): multiple definition of `__cudart499'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x69de0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart742':
      (.text+0x6f560): multiple definition of `__cudart742'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x69e70): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x818): multiple definition of `__cudart1027'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x840): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaGraphAddMemcpyNode1D':
      (.text+0x53100): multiple definition of `cudaGraphAddMemcpyNode1D'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x51140): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMallocHost':
      (.text+0x46690): multiple definition of `cudaMallocHost'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x43a90): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0xb68): multiple definition of `__cudart1392'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x278): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1157':
      (.text+0xbbd0): multiple definition of `__cudart1157'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x60b0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaGraphExecHostNodeSetParams':
      (.text+0x59750): multiple definition of `cudaGraphExecHostNodeSetParams'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x57440): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart1370':
      (.text+0xacb0): multiple definition of `__cudart1370'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xdcf0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMallocArray':
      (.text+0x46a20): multiple definition of `cudaMallocArray'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x43e20): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x240): multiple definition of `__cudart1448'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x9c0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart983':
      (.text+0xa080): multiple definition of `__cudart983'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x6490): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaLaunchHostFunc_ptsz':
      (.text+0x457c0): multiple definition of `cudaLaunchHostFunc_ptsz'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x42f60): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMemcpyFromArray_ptds':
      (.text+0x4d350): multiple definition of `cudaMemcpyFromArray_ptds'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x4a320): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaEventRecord':
      (.text+0x601f0): multiple definition of `cudaEventRecord'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x5d7a0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart619':
      (.text+0x6e160): multiple definition of `__cudart619'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x6c2b0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart884':
      (.text+0x6d80): multiple definition of `__cudart884'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x1740): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart650':
      (.text+0x9d20): multiple definition of `__cudart650'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x5670): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMemcpyPeerAsync':
      (.text+0x4aaf0): multiple definition of `cudaMemcpyPeerAsync'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x47af0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0xab8): multiple definition of `__cudart1002'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xdee0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x28): multiple definition of `__cudart1321'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.bss+0x6f0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `cudaMallocPitch':
      (.text+0x46840): multiple definition of `cudaMallocPitch'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x43c40): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o):(.bss+0x108): multiple definition of `__cudart1457'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0xb5c0): first defined here
      /usr/bin/ld: /usr/local/cuda-12.1/lib64/libcudart_static.a(cudart_static.o): in function `__cudart780':
      (.text+0x2e230): multiple definition of `__cudart780'; /usr/lib/x86_64-linux-gnu/libcudart_static.a(cudart_static.o):(.text+0x2b830): first defined here
      collect2: error: ld returned 1 exit status
      gmake[2]: *** [CMakeFiles/pycolmap.dir/build.make:139：/home/netease/pycolmap-master/build/lib.linux-x86_64-cpython-310/pycolmap.cpython-310-x86_64-linux-gnu.so] 错误 1
      gmake[1]: *** [CMakeFiles/Makefile2:100：CMakeFiles/pycolmap.dir/all] 错误 2
      gmake: *** [Makefile:91：all] 错误 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/netease/pycolmap-master/setup.py", line 83, in <module>
          setup(
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/netease/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/netease/pycolmap-master/setup.py", line 35, in run
          self.build_extension(ext)
        File "/home/netease/pycolmap-master/setup.py", line 78, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
        File "/home/netease/anaconda3/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycolmap

```
I build colmap with "cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=60" and success, my GPU is nvidia GTX 1060.

**Comment by VindenChen** [comment]
If directly download "pycolmap-master.zip" from github, make sure the directory "pybind11" is not empty.

**Comment by xjcvip007** [comment]
@VindenChen thanks for your reply, I make sure the pybind11 is not empty, I download the pybind11 from https://github.com/pybind/pybind11/tree/f7b499615e14d70ab098a20deb0cdb3889998a1a and put it to the corresponding location.

**Comment by sarlinpe** [comment]
These are linking issues, they have probably been solved by the recent refactorings of COLMAP's build system. Feel free to re-open if this still occurs at HEAD.
