### ISSUE TITLE
Build isn't working

### ISSUE THREAD

**Issue by Techinix** [colmap/pycolmap#160]
i skimmed through the other issues and this seems to be a classic problem , i just wanted to ask if there's any issue with building pycolmap atm ? i can't get around it , here's the error that pops whenever i try building : 

-- Build files have been written to: /tmp/pip-req-build-wz4575ta/build/temp.linux-x86_64-3.8
    [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
    In file included from /tmp/pip-req-build-wz4575ta/pybind11/include/pybind11/eigen.h:12,
                     from /tmp/pip-req-build-wz4575ta/main.cc:3:
    /tmp/pip-req-build-wz4575ta/pybind11/include/pybind11/eigen/matrix.h:27:10: fatal error: Eigen/Core: No such file or directory
       27 | #include <Eigen/Core>
          |          ^~~~~~~~~~~~
    compilation terminated.
    make[2]: *** [CMakeFiles/pycolmap.dir/build.make:76: CMakeFiles/pycolmap.dir/main.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/pycolmap.dir/all] Error 2
    make: *** [Makefile:91: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-wz4575ta/setup.py", line 83, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-wz4575ta/setup.py", line 35, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-wz4575ta/setup.py", line 78, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by Skydes** [comment]
The dev branch of COLMAP is super unstable lately, please use tags v.0.4.0 for pycolmap and 3.8 for COLMAP. We'll fix everything once major changes in COLMAP are completed.

**Comment by Techinix** [comment]
is this still the case ??

**Comment by sarlinpe** [comment]
PyCOLMAP's HEAD now tracks COLMAP's HEAD again. Some APIs changed a bit but the documentation is updated accordingly with PR https://github.com/colmap/pycolmap/pull/175. Still, expect additional major API changes in the coming weeks.

**Comment by sarlinpe** [comment]
Closing due to inactivity.
